### ISSUE TITLE
Dependency on `psycopg` to include `[binary]` extra

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pgstac#105]
Similar to #103, `pypgstac` needs to declare extras on `psycopg` - `psycopg[binary]`.

**Comment by vincentsarago** [comment]
FYI in titiler-pgstac we let the user decide to use binary, native or c version https://github.com/stac-utils/titiler-pgstac/blob/master/setup.py#L23-L26

https://github.com/stac-utils/titiler-pgstac#psycopg-requirement

**Comment by lossyrob** [comment]
Fixed by #107 - feel free to follow-up with separate packages for native/c/binary versions
