### ISSUE TITLE
Does pgstac Query Extension support work with `neq` operator?

### ISSUE THREAD

**Issue by philvarner** [stac-utils/pgstac#120]
I just filed https://github.com/stac-utils/stac-fastapi/issues/408 against stac-fastapi b/c the Query Extension "not equals" operator is incorrectly set to be `ne` instead of `neq`. This issue is to proactively ask if pgstac works with neq as the operator? I believe the current error I'm seeing is from the object validation within stac-fastapi, but once that's fixed, it may trigger a similar bug in pgstac, and I wanted to get ahead of that.

**Comment by duckontheweb** [comment]
Judging from [this migration](https://github.com/stac-utils/pgstac/blame/cb03727ebbcc49fa6a1f4775772d0deeb16552da/pypgstac/pypgstac/migrations/pgstac.0.2.4-0.2.7.sql#L26) it looks like it supports both.

**Comment by gadomski** [comment]
Closing as "yes" b/c I concur with @duckontheweb.
