### ISSUE TITLE
Ingest data by multiple users

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/pgstac#126]
Imagine that we have 2 users `user1` and `user2` which can ingest data into the database:

```sql
GRANT pgstac_ingest TO user1;
GRANT pgstac_ingest TO user2;
```

During the data ingestion process pgstac creates `_items_N` tables  and makes the current user as an owner:

```sql
postgis=# \dt;
                        List of relations
 Schema |         Name         |       Type        |    Owner     
--------+----------------------+-------------------+--------------
 pgstac | _items_1             | table             | user1
 ```

Now if `user2` try to ingest data belonging to the same collection it might end up calling `ALTER TABLE` from [here](https://github.com/stac-utils/pgstac/blob/7b5ff0767a4dd47cd5638defa4434e4bf9172612/sql/002_collections.sql#L381) which will fail with `must be owner of table _items_1` error.

**Comment by bitner** [comment]
In PR #160, the migrations ensure that all pgstac objects are owned by the pgstac_admin role. All functions that maintain/update the partition structure and constraints are now marked as SECURITY DEFINER meaning that when they are run by any user who has permissions to use that function, they will be run as the pgstac_admin role and all partitions will still be owned by pgstac_admin.
