### ISSUE TITLE
Special characters in password

### ISSUE THREAD

**Issue by drnextgis** [stac-utils/pgstac#138]
If the database password contains special characters then it is not possible just to copy-paste it to the terminal as part of the `--dsn` while using `pypgstac load`.

To overcome the issue we have to do something like:

```python
from urllib.parse import quote
print(quote(password))
```

It would be nice to add support of configuring DSN via env vars.

**Comment by bitner** [comment]
pypgstac inherits the environment variables that are available with psycopg if there is no dsn provided. This is actually how I normally use pgstac as I generally set these variables in my environment for use with tools like psql as well.

These are the standard libpq environment variables:
PGUSER
PGHOST
PGDATABASE
PGPASSWORD
PGPORT
PGSSLMODE

**Comment by drnextgis** [comment]
It woks like a charm. Thanks!
