### ISSUE TITLE
Search does not account for items that are in multiple collections

### ISSUE THREAD

**Issue by mrob95** [stac-utils/pgstac#192]
According to the spec, item ids "should be unique within the Collection that contains the Item." (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields).

This means that it is possible to have an item with the same ID in multiple collections. Pgstac does not take this into account when constructing search queries though. For example a query with body:
```
{
    "ids": [
        "fc92ee93-5707-4110-91e9-c4ed000a7462"
    ],
    "collections": [
        "b6eb0ede-9eed-4e7e-aa9c-b50887ce252d",
        "4f939cb1-58cf-470a-b1ba-274c641068c4"
    ]
}
```

Runs the following SQL (version 0.7 .10):
```
2023-07-03 16:06:32.099 UTC [924] STATEMENT:  SELECT search($1::jsonb);
2023-07-03 16:06:32.110 UTC [924] LOG:  QUERY:
           SELECT * FROM items
           WHERE
           datetime >= '-infinity' AND datetime < 'infinity'
           AND (id = ANY ('{fc92ee93-5707-4110-91e9-c4ed000a7462}')  AND collection = ANY ('{b6eb0ede-9eed-4e7e-aa9c-b50887ce252d,4f939cb1-58cf-470a-b1ba-274c641068c4}') )
           ORDER BY datetime DESC, id DESC
           LIMIT '1'
```

The `LIMIT '1'` is incorrect here as there could be an item with that ID in both of the collections passed.

**Comment by mrob95** [comment]
It looks like https://github.com/stac-utils/pgstac/pull/181/files introduced this as an optimisation. I don't think it's valid though unfortunately. You could potentially set a limit to num_items*num_collections if there are collections specified as well but you probably lose most of the performance benefit in that case.

**Comment by bitner** [comment]
Ah, this is a good catch. We did introduce the limit for ids searches as an optimization and I didn't think of the case of duplicate ids in multiple collections. I'll need to think about if there is a way we can maintain the optimization while still handle duplicate item ids.
