### ISSUE TITLE
remove psycopg2 from the dev dependencies

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/pgstac#196]
https://github.com/stac-utils/pgstac/blob/45b1f96e0e77a34cac9219944ed8064134c2dbaf/src/pypgstac/pyproject.toml#L49

we should be using only Version >=3 of `psycopg`

**Comment by bitner** [comment]
psycopg2-binary is required for the migra tool that is used to build migrations

**Comment by drnextgis** [comment]
I believe adding a comment to https://github.com/stac-utils/pgstac/blob/main/src/pypgstac/pyproject.toml to explain the purpose of having `psycopg2-binary` would be worthwhile

**Comment by bitner** [comment]
I'm reworking the docker images right now, I can probably just make the script that builds the migrations separate from pypgstac and use a separate docker image for it.

**Comment by bitner** [comment]
moved the dependency to optional under migra.
