### ISSUE TITLE
Connecting pgstac to an external Postgresql

### ISSUE THREAD

**Issue by randyberos** [stac-utils/pgstac#203]
Is it possible to connect the pgstac to an external Postgresql db instead of starting with a postgres image in the Dockerfile?

**Comment by mmcfarland** [comment]
Hi @randyberos, you can install pgstac into a PostsgreSQL database by using the [pypgstac utility library](https://stac-utils.github.io/pgstac/pypgstac/). Check the documentation for complete details, but this typically involves installing pypgstac on a computer that can connect to your database, then simply running the `pypgstac migrate --dsn ${DSN}` command. This will migrate the database to the latest pgstac version within that version of pypgstac. You can also provide a `--toversion` flag to specify the pgstac version explicitly.

**Comment by randyberos** [comment]
Thanks for the prompt response. 

Upon trying the `pypgstac migrage` I am having a `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 8173: character maps to <undefined>` error.

I am trying to migrate pystac to a Postgresql 14 database hosted in Google cloud console. Do you know what is causing this error?

**Comment by mmcfarland** [comment]
I'm not familiar with that particular error, but the `migrate` command does take a `--debug` option that should output more verbose logging which could help pinpoint the issue.

**Comment by randyberos** [comment]
Finally fixed the problem. The `pypgstac migrate` did not work in a Windows system however it worked in a Linux system.

Thank you very much for the help!
