### ISSUE TITLE
error message: pglogger() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pgstac#30]
I'm seeing in logging output:

```
ERROR    asyncio:base_events.py:1707 Unhandled exception in asyncpg log message listener callback <function pglogger at 0x7fc70bb4c280>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/asyncpg/connection.py", line 1435, in _call_log_listener
    cb(con_ref, message)
TypeError: pglogger() takes 1 positional argument but 2 were given
```

This doesn't error out code so is really more of a warning, but perhaps there's a mispatch on the pglogger method params and the callback signature asyncpg expects

**Comment by bitner** [comment]
@lossyrob the changes in #27 stripped out a lot of the logging code (including this) that I used a lot to test things when first debugging but are not of much use in action.
