### ISSUE TITLE
Strange behavior of PgSTAC Catalog when querying using PySTAC client.

### ISSUE THREAD

**Issue by MathewNWSH** [stac-utils/pgstac#308]
Hi!
During the last tests, I noticed strange behavior with my catalog when querying using the PySTAC client. Specifically, regardless of the query, it always returns a maximum of 10 items.

```python
import pystac_client
import ipyleaflet
import geogif
import stackstac
import os
import pystac_client

lon, lat = 21, 52

# Main endpoint for STAC
URL='https://stac-cdse.eu/'
catalog = pystac_client.Client.open(URL)
catalog.add_conforms_to("ITEM_SEARCH")

items = catalog.search(
    collections=['sentinel-2-l2a'],
    intersects=dict(type="Point", coordinates=[lon, lat]),
    datetime="2020-09-15/2024-09-16").item_collection()
```
![image](https://github.com/user-attachments/assets/ac8b1c21-fe3b-4f16-b0e7-25307a53c7c3)
Increasing `max_items` parameter does nothing :/

**While using `pgstac.demo.cloudferro.com` with analogical query there was no such problem.**

1. stac-cdse.eu pgstac database deployment:

```console
#!/bin/bash
# Update the package list
apt-get update

# Install nano
apt install -y nano

# Install required packages with automatic yes
apt-get install -y ca-certificates curl

# Create the directory for Docker keyrings
install -y -m 0755 -d /etc/apt/keyrings

# Download the Docker GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

# Ensure the keyring file is readable
chmod a+r /etc/apt/keyrings/docker.asc

# Add Docker repository to APT sources
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
$(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update the package list again
apt-get -y update

# Install Docker components with automatic yes
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Install pypgstac
python3 -m pip install pypgstac[psycopg]

# Export initial env variables:
# for pypgstsac
export POSTGRES_USER=
export POSTGRES_PASSWORD=
export POSTGRES_DB=
export PGUSER=
export PGPASSWORD=
export PGDATABASE=

export PGHOST=0.0.0.0
export PGPORT=5432

# for docker
export postgres_ram="200g"
export postgres_cpus=62
export POSTGRES_IMAGE="postgis/postgis:16-master"

# let's make sure that we only need to export those only once
echo "export POSTGRES_USER=${POSTGRES_USER}" >> /home/eouser/.bashrc
echo "export POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> /home/eouser/.bashrc
echo "export POSTGRES_DB=${POSTGRES_DB}" >> /home/eouser/.bashrc
echo "export PGUSER=${PGUSER}" >> /home/eouser/.bashrc
echo "export PGPASSWORD=${PGPASSWORD}" >> /home/eouser/.bashrc
echo "export PGDATABASE=${PGDATABASE}" >> /home/eouser/.bashrc
echo "export PGHOST=${PGHOST}" >> /home/eouser/.bashrc
echo "export PGPORT=${PGPORT}" >> /home/eouser/.bashrc

# Run pgstac via installed docker:
docker run -d \
  --name stac-db \
  --restart unless-stopped \
  --memory="${postgres_ram}" \
  --cpus="${postgres_cpus}" \
  -e POSTGRES_USER=${POSTGRES_USER} \
  -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
  -e POSTGRES_DB=${POSTGRES_DB} \
  -e PGUSER=${PGUSER} \
  -e PGPASSWORD=${PGPASSWORD} \
  -e PGDATABASE=${PGDATABASE} \
  -p 5432:5432 \
  -v stac-db-data:/var/lib/postgresql/data \
  ${POSTGRES_IMAGE}

# Base migrations install PgSTAC into a database with no current PgSTAC installation
pypgstac migrate
```

2. Populating Catalogues:
```
pypgstac load collections https://s3.fra1-2.cloudferro.com/swift/v1/poland-stac/collection-sentinel-2-l2a.json
pypgstac load items https://s3.fra1-2.cloudferro.com/swift/v1/poland-stac/poland-data.json --method upsert
pypgstac load items https://s3.fra1-2.cloudferro.com/swift/v1/marcin-kluczek/chunk_aa1.json
pypgstac load items https://s3.fra1-2.cloudferro.com/swift/v1/marcin-kluczek/chunk_aa0.json

```

3. Deployment stac-fastAPI:
behavior was tested with 3 different versions of FastAPI
main
3.0.0
2.4.11 (the one used for pgstac.demo.cloudferro.com)

with the same result for each.

**Used postgres versions:
postgis/postgis:16-master - stac-cdse.eu
ghcr.io/stac-utils/pgstac:v0.8.4 - pgstac.demo.cloudferro.com**

If this issue is related to the image being used, I would kindly ask for information or a guide on deploying PgSTAC on images other than the original ones.

Best,
Marcin

**Comment by vincentsarago** [comment]
@MathewNWSH the datetime do not follow the spec can you try with '1990-12-31T23:59:61Z' format 

Or maybe I'm not understanding the issue, are you complaining about the number of items being return or the fact that it the same 10 items? 

if it's about the number of items, there is a `limit` parameter which default to 10, so you can adjust this by passing `limit=100`

**Comment by MathewNWSH** [comment]
Hey,

Yes, I completely meant that it's still returning only 10 products :)
I'm familiar with the `limit` parameter, but it was kind of weird for me since I didn't need to provide it for my other catalog, and it was still returning the data (even if it exceeds the number of 10).

**Is there an environment variable increasing the default limit in ghcr.io/stac-utils/pgstac:v0.8.4?**

Anyway, a big thank you!

**Comment by vincentsarago** [comment]
the default limits comes from https://github.com/stac-utils/stac-fastapi/blob/753341f18d6c3d0454efef52d0ff841cfa3215f7/stac_fastapi/types/stac_fastapi/types/search.py#L176-L190

10 is the default defined by the specification

> limit The limit parameter follows the same semantics of the OAFeat Item resource limit parameter. The value is a suggestion to the server as to the maximum number of Item objects the client would prefer in the response. The server may return fewer Item objects, but must not return more. The OpenAPI specification defines the default and maximum values for this parameter. The base specifications define these with a default of 10 and a maximum of 10000, but implementers may choose other values to advertise through their service-desc endpoint. If the limit parameter value is greater than the advertised maximum limit, the server must act as if the request were for the maximum and not return an error.

ref: https://github.com/radiantearth/stac-api-spec/tree/release/v1.0.0/item-search#query-parameter-table

You can built your own stac-fastapi-pgstac application with other default than 10 (ref: https://github.com/stac-utils/stac-fastapi/discussions/737)

**Comment by vincentsarago** [comment]
@MathewNWSH are we good to close this?

**Comment by MathewNWSH** [comment]
> @MathewNWSH are we good to close this?

Yes, thanks again
