### ISSUE TITLE
Spatial partitions for big collections

### ISSUE THREAD

**Issue by betolink** [stac-utils/pgstac#313]
Doing a quick look at the documentation I couldn't find information about spatial partitioning, the use case I'm interested in is when we have a few collections but they have a lot of items, say all of Landsat/Sentinel in multiple versions (10M+). Is something like this available? I'm working with time series at sub-continental scale, e.g. "all of the mission for southern Greenland where..."
I wonder if global grids could be used to define how to partition each collection.

**Comment by betolink** [comment]
Thanks for the detailed answer, we're scanning about 30M records (all landsats+sentinels) and I was looking to further optimize the partitioning to take advantage of parallel execution over the geom index. Just out of curiosity, do you guys have benchmarks we can take a look at? no worries if not, I'm closing this issue, Thanks!

**Comment by bitner** [comment]
Sorry, we don't have any benchmarks, but based on other experience, I would not expect spatial partitioning to make any difference (and actually, there is a good chance it would make things worse) in the pgstac context.
