### ISSUE TITLE
Multiple entries of version in pgstc.migrations table

### ISSUE THREAD

**Issue by jonas-eberle** [stac-utils/pgstac#51]
Running the pypgstac migrate command from a previous version to a new version leads to multiple entries of the final version in the pgstac.migrations table: 

```Migrating from 0.2.4 to 0.3.3.
Running migrations for ['pgstac.0.2.4-0.2.7.sql', 'pgstac.0.2.7-0.2.8.sql', 'pgstac.0.2.8-0.2.9.sql', 'pgstac.0.2.9-0.3.0.sql', 'pgstac.0.3.0-0.3.1.sql', 'pgstac.0.3.1-0.3.2.sql', 'pgstac.0.3.2-0.3.3.sql'].
pgstac version 0.3.3
```

```postgis=# select * from pgstac.migrations;
 version |           datetime
---------+-------------------------------
 0.2.4   | 2021-07-23 00:00:00+00
 0.2.7   | 2021-09-03 09:02:22.32407+00
 0.3.3   | 2021-09-03 09:02:22.360333+00
 0.2.8   | 2021-09-03 09:02:22.362009+00
 0.3.3   | 2021-09-03 09:02:22.362903+00
 0.2.9   | 2021-09-03 09:02:22.364059+00
 0.3.3   | 2021-09-03 09:02:22.364059+00
 0.3.0   | 2021-09-03 09:02:22.366378+00
 0.3.3   | 2021-09-03 09:02:22.366378+00
 0.3.1   | 2021-09-03 09:05:24.690869+00
 0.3.3   | 2021-09-03 09:05:24.690869+00
 0.3.2   | 2021-09-03 09:05:24.716236+00
 0.3.3   | 2021-09-03 09:05:24.716236+00
 0.3.3   | 2021-09-03 09:05:24.723922+00
 0.3.3   | 2021-09-03 09:05:24.723922+00
(15 rows)
```

For any migration file (e.g., 0.2.4 to 0.2.7) two inserts are currently conducted: 

1. From the migration file 
https://github.com/stac-utils/pgstac/blob/main/pypgstac/pypgstac/migrations/pgstac.0.2.4-0.2.7.sql#L313

2. From the python script (which inserts always to latest version to migrate to - in my case 0.3.3): 
https://github.com/stac-utils/pgstac/blob/main/pypgstac/pypgstac/migrate.py#L160-L170

I think this can be resolved by removing the insert statement from the python script?

**Comment by kylebarron** [comment]
I believe I also saw this in https://github.com/stac-utils/pgstac/issues/49
