### ISSUE TITLE
CI for publishing pypgstac

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/pgstac#6]
I noticed that the latest version pypgstac on pypi is 0.2.4. The main branch has a version of 0.2.3, and there's not tags for all released versions.

We should set up GitHub Actions to do the publishing, much like we are doing in [pystac](https://github.com/stac-utils/pystac/blob/main/.github/workflows/release.yml). That way releases happen on each GitHub release, and the python package is published by CI against tagged versions. This will require the `stacutils` user to be made a maintainer on the pypgstac pypi repository.

**Comment by kylebarron** [comment]
:+1: Was just going to make an issue that there aren't Git tags for every issue. Would be nice to have them in sync with what gets pushed to pypi.
