### ISSUE TITLE
Intersects geometry in search appears limited to 8K bytes in version >= 0.3.5

### ISSUE THREAD

**Issue by zstatmanweil** [stac-utils/pgstac#71]
When running searches that include an "intersects" for complex geometries, I am seeing this error:

`ERROR:  index row requires 293792 bytes, maximum size is 8191`

The "293792 bytes" seems to correspond to the size of the input geometry. 

The error does not occur for simpler geometries (I ran one that was a simple polygon covering the same area loosely as the complex polygon) nor in earlier versions of pgstac. Below is the stack trace from the database when running a search with one collection and an intersects of California, although I left off the first two notices of `NOTICE:  ARGS after array cleaning: ` since the geometry value is so long. Happy to provide the specific California geometry if needed.

```
NOTICE:  Checking if update is needed.
NOTICE:  Stats Last Updated: <NULL>
NOTICE:  TTL: 1 day, Age: <NULL>
NOTICE:  Context: off, Existing Total: <NULL>
NOTICE:  Time for just the explain: 00:00:00.428574
NOTICE:  Time for explain + join: 00:00:00.431062

ERROR:  index row requires 293792 bytes, maximum size is 8191
CONTEXT:  SQL statement "INSERT INTO search_wheres SELECT sw.*

    ON CONFLICT (_where)

    DO UPDATE

        SET

            lastused = sw.lastused,

            usecount = sw.usecount,

            statslastupdated = sw.statslastupdated,

            estimated_count = sw.estimated_count,

            estimated_cost = sw.estimated_cost,

            time_to_estimate = sw.time_to_estimate,

            partitions = sw.partitions,

            total_count = sw.total_count,

            time_to_count = sw.time_to_count"
PL/pgSQL function where_stats(text,boolean) line 189 at SQL statement
SQL statement "SELECT where_stats(search._where, updatestats)"
PL/pgSQL function search_query(jsonb,boolean,jsonb) line 41 at PERFORM
PL/pgSQL function search(jsonb) line 71 at assignment
SQL state: 54000
```
Thank you!

**Comment by davidraleigh** [comment]
What is the vertex count on that geometry?

At Planet I think we forced customers to submit about 400 vertex geometries to prevent to complex of computational geometry demand on intersection tests. Or maybe it was a bandwidth thing? Either way, is there a reason it has to have all the vertices? Maybe some of that work can be pushed onto the client?

**Comment by zstatmanweil** [comment]
Good question! It is a very complex polygon so ~10K vertices. I think the benefit of allowing for somewhat detailed polygons for larger areas is then you can be very specific on what you capture with the intersects search if your items happen to have relatively small geometries. 10K vertices is more than needed, but the earlier versions of pgstac didn't have this limitation so I thought maybe it wasn't on purpose.

**Comment by davidraleigh** [comment]
@zstatmanweil the maintainers probably did it on purpose. probably thinking of high availability for services and not letting computational geometry bog things down. 

But I agree with you, that the vertex limit should be someplace else in the service definition, so STAC maintainers who care less about availability and more about detail can have that option.

Say hello to Chips and Caitlin for me!

**Comment by zstatmanweil** [comment]
@davidraleigh , haha will do! Its such a small geospatial world :) 

Well I am happy to close it if the maintainers say it is as desired.

**Comment by bitner** [comment]
It looks like if we change the primary key on the search_wheres table to use a hash that we can get rid of this issue. While this is definitely a bug, I would expect that performance with use geometries that large isn't going to be that great in any case!
