### ISSUE TITLE
Partitioned tables cannot have BEFORE / FOR EACH ROW triggers

### ISSUE THREAD

**Issue by captaincoordinates** [stac-utils/pgstac#90]
Executing `migrations/pgstac.0.4.3.sql` on PostgreSQL 12.8 fails with the following
```
"items" is a partitioned table
Partitioned tables cannot have BEFORE / FOR EACH ROW triggers
```
Issue #63 reported the same error, and the issue was later closed by the same user reporting "Forgot to install pg_partman.", indicating that installing pg_partman solved the problem. However PR #66 removed pg_partman from the list of required extensions. My testing suggests pg_partman does not make a difference.

pgstac.0.3.4.sql fails in the same way on PostgreSQL 12.8.
pgstac.0.4.3.sql succeeds in PostgreSQL 13.4 with no further changes besides version number.

To reproduce: https://github.com/captaincoordinates/pgstac-pg12-test/

1. Does pgstac still support PostgreSQL 12.x?
2. Is pg_partman required for 12.x?

Any feedback much appreciated 🙏

**Comment by bitner** [comment]
pg_partman is NOT required anymore. PGStac includes its own functionality for managing partitions. 

Yes, it appears a change was made in partition handling that requires PostgreSQL 13+. I will update the documentation to indicate that.

Note that the current hard-coded 1 week duration layout of partitions will be changing at version 0.5 (see issue #83)

**Comment by captaincoordinates** [comment]
The only reason we need 12 is because AWS RDS Proxy currently only supports up to 12 in PostgreSQL and Aurora-PostgreSQL, even though RDS itself supports 13. Amazon is frustratingly slow in incorporating new versions but RDS Proxy provides real benefits in our stack.

Support for 12 would be nice but I don't think our needs warrant the kind of effort that might be required to work through this. I mainly just wanted to confirm that I had correctly interpreted the situation before committing time to other options, like PgBouncer in place of RDS Proxy.

I appreciate your input, and agree it's appropriate to close this issue with a documentation change.

**Comment by drnextgis** [comment]
[Amazon RDS Proxy now supports PostgreSQL major version 13](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-rds-proxy-supports-postgresql-major-version-13/)
